name: SelfUp
options:
  bundleIdPrefix: com.farelevan.selfup
targets:
  SelfUp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SelfUp
    dependencies:
      - target: SelfUpWidgets
    settings:
      base:
        INFOPLIST_FILE: SelfUp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.farelevan.selfup.SelfUp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
      configs:
        debug:
          CODE_SIGN_STYLE: Automatic
        release:
          CODE_SIGN_STYLE: Automatic
  SelfUpWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SelfUpWidgets
      - path: SelfUp/Features/Shared/SelfUpStyle.swift
      - path: SelfUp/Services/WidgetDataStore.swift
    settings:
      base:
        INFOPLIST_FILE: SelfUpWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.farelevan.selfup.SelfUp.SelfUpWidgets
        DEVELOPMENT_TEAM: ""
      configs:
        debug:
          CODE_SIGN_STYLE: Automatic
        release:
          CODE_SIGN_STYLE: Automatic
  SelfUpTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SelfUpTests
    dependencies:
      - target: SelfUp
    settings:
      configs:
        debug:
          CODE_SIGN_STYLE: Automatic
        release:
          CODE_SIGN_STYLE: Automatic

